# Generated by Django 4.1.4 on 2022-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_categordb'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('DISCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('PRICE', models.CharField(blank=True, max_length=100, null=True)),
                ('QUNTITY', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
