# Generated by Django 4.1.4 on 2022-12-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_prodetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodetails',
            old_name='DISCRIPTION',
            new_name='DESCRIPTION',
        ),
    ]
