# Generated by Django 4.1.4 on 2023-01-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_category_prodetails_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('SUBJECT', models.CharField(blank=True, max_length=100, null=True)),
                ('MESSAGE', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
