# Generated by Django 4.1.4 on 2023-01-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='EMAIL',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='MESSAGE',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='NAME',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='SUBJECT',
            new_name='Subject',
        ),
    ]
